import { Component, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { BookService } from '../../../services/book.service';
import { TopicService } from '../../../services/topic.service';
import { Book } from '../../../models/book.model';
import { Topic } from '../../../models/topic.model';
import { CommonModule } from '@angular/common';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap'; // For ngbTooltip

@Component({
  selector: 'app-book-create',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, NgbModule],
  templateUrl: './book-create.html',
})
export class BookCreateComponent implements OnInit {
  bookForm: FormGroup;
  showSuccess: boolean = false;
  topics: Topic[] = [];

  constructor(
    private fb: FormBuilder,
    private bookService: BookService,
    private topicService: TopicService,
    private router: Router
  ) {
    this.bookForm = this.fb.group({
      title: ['', Validators.required],
      author: ['', Validators.required],
      topic: [[], Validators.required], // Array of topic IDs
    });
  }

  ngOnInit() {
     this.topicService.getTopics({ page: 1, limit: 100 }).subscribe({
      next: (response) => (this.topics = response.topics),
      error: () => (this.topics = []),
    });
  }

  onSubmit() {
    if (this.bookForm.valid) {
      const formValue = this.bookForm.value;
      const book: Book = {
        id: '', // Will be generated by backend
        title: formValue.title,
        author: formValue.author,
        topic: formValue.topic, // Use the selected topic IDs directly
      };
      this.bookService.createBook(book).subscribe({
        next: () => {
          this.showSuccess = true;
          setTimeout(() => {
            this.showSuccess = false;
            this.bookForm.reset();
            this.router.navigate(['/books']);
          }, 2000);
        },
        error: (error) => {
          this.showSuccess = false;
          console.error('Error creating book:', error);
          // Optionally show an error message
        },
      });
    }
  }
}